name: Continuous Integration

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Run a hello script
        run: echo "Hello, world! GitHub Actions is working."
